
default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-52-5-247-46.compute-1.amazonaws.com
  port: 5432
  database: dcj1je0h6qee6k
  pool: 5
  username: myuuxwzeaqrumd
  password: 2a40d30a11a31e9b95f8092f153edb43ea7fc78b92256e7d7b51163fbd7401f0

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
